server:
  port: 8080
spring:
  application:
    name: ethan-async


task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 20
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50